apiVersion: v1
kind: Namespace
metadata:
  name: bro
spec:
  finalizers:
    - kubernetes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi
  namespace: bro
spec:
  replicas: 2
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: poi
          image: registrybro8635.azurecr.io/bro_team/poi:latest
          env:
            - name: SQL_USER
              valueFrom:
                secretKeyRef:
                  name: mssqlconfig
                  key: username
            - name: SQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mssqlconfig 
                  key: password
            - name: SQL_SERVER
              valueFrom:
                secretKeyRef:
                  name: mssqlconfig
                  key: server
            - name: SQL_DBNAME
              valueFrom:
                secretKeyRef:
                  name: mssqlconfig
                  key: database
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: '500m'
              memory: 1G
            limits:
              cpu: '256'
              memory: 11400G
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips
  namespace: bro
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trips
  template:
    metadata:
      labels:
        app: trips
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: trips
          image: registrybro8635.azurecr.io/bro_team/trips:latest
          env:
            - name: SQL_USER
              valueFrom:
                secretKeyRef:
                  name: mssqlconfig
                  key: username
            - name: SQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mssqlconfig 
                  key: password
            - name: SQL_SERVER
              valueFrom:
                secretKeyRef:
                  name: mssqlconfig
                  key: server
            - name: SQL_DBNAME
              valueFrom:
                secretKeyRef:
                  name: mssqlconfig
                  key: database
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: '500m'
              memory: 1G
            limits:
              cpu: '256'
              memory: 11400G
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile
  namespace: bro
spec:
  replicas: 2
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: userprofile
          image: registrybro8635.azurecr.io/bro_team/userprofile:latest
          env:
            - name: SQL_USER
              valueFrom:
                secretKeyRef:
                  name: mssqlconfig
                  key: username
            - name: SQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mssqlconfig 
                  key: password
            - name: SQL_SERVER
              valueFrom:
                secretKeyRef:
                  name: mssqlconfig
                  key: server
            - name: SQL_DBNAME
              valueFrom:
                secretKeyRef:
                  name: mssqlconfig
                  key: database
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: '200m'
              memory: 1G
            limits:
              cpu: '256'
              memory: 11400G

---
apiVersion: v1
kind: Service
metadata:
  name: poi-service
  namespace: bro
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      name: port80
      port: 80
      protocol: TCP
  selector:
    app: poi
---
apiVersion: v1
kind: Service
metadata:
  name: trip-service
  namespace: bro
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      name: port80
      port: 80
      protocol: TCP
  selector:
    app: trip
---
apiVersion: v1
kind: Service
metadata:
  name: userprofile
  namespace: bro
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      name: port80
      port: 80
      protocol: TCP
  selector:
    app: trip

