apiVersion: v1
kind: Namespace
metadata:
  name: bro
spec:
  finalizers:
    - kubernetes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi
  namespace: bro
spec:
  replicas: 2
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: poi
          image: registrybro8635.azurecr.io/bro_team/poi:latest
          env:
            - name: SQL_USER
              valueFrom:
                secretKeyRef:
                  name: mssqlconfig
                  key: username
            - name: SQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mssqlconfig 
                  key: password
            - name: SQL_SERVER
              valueFrom:
                secretKeyRef:
                  name: mssqlconfig
                  key: server
            - name: SQL_DBNAME
              valueFrom:
                secretKeyRef:
                  name: mssqlconfig
                  key: database
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: '500m'
              memory: 1G
            limits:
              cpu: '256'
              memory: 11400G
---
apiVersion: v1
kind: Service
metadata:
  name: poi-service
  namespace: default-1675178595762
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      name: port80
      port: 80
      protocol: TCP
  selector:
    app: poi
---
apiVersion: v1
kind: Secret
metadata:
  name: mssqlconfig
  namespace: bro
type: Opaque
data:
# all of the below need to be encoded in base64
  username: 
  password: 
  server: 
  database: 