apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi
  namespace: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: poi
          image: registrybro8635.azurecr.io/bro_team/poi:latest
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: SQL_USER
              valueFrom:
                secretKeyRef:
                  name: mssqlconfig
                  key: username
            - name: SQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mssqlconfig 
                  key: password
            - name: SQL_SERVER
              valueFrom:
                secretKeyRef:
                  name: mssqlconfig
                  key: server
            - name: SQL_DBNAME
              valueFrom:
                secretKeyRef:
                  name: mssqlconfig
                  key: database
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: '500m'
              memory: 1G
            limits:
              cpu: '256'
              memory: 11400G
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips
  namespace: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trips
  template:
    metadata:
      labels:
        app: trips
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: trips
          image: registrybro8635.azurecr.io/bro_team/trips:latest
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: SQL_USER
              valueFrom:
                secretKeyRef:
                  name: mssqlconfig
                  key: username
            - name: SQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mssqlconfig 
                  key: password
            - name: SQL_SERVER
              valueFrom:
                secretKeyRef:
                  name: mssqlconfig
                  key: server
            - name: SQL_DBNAME
              valueFrom:
                secretKeyRef:
                  name: mssqlconfig
                  key: database
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: '500m'
              memory: 1G
            limits:
              cpu: '256'
              memory: 11400G
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile
  namespace: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: userprofile
          image: registrybro8635.azurecr.io/bro_team/userprofile:latest
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: SQL_USER
              valueFrom:
                secretKeyRef:
                  name: mssqlconfig
                  key: username
            - name: SQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mssqlconfig 
                  key: password
            - name: SQL_SERVER
              valueFrom:
                secretKeyRef:
                  name: mssqlconfig
                  key: server
            - name: SQL_DBNAME
              valueFrom:
                secretKeyRef:
                  name: mssqlconfig
                  key: database
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: '200m'
              memory: 1G
            limits:
              cpu: '256'
              memory: 11400G
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-java
  namespace: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-java
  template:
    metadata:
      labels:
        app: user-java
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: user-java
          image: registrybro8635.azurecr.io/bro_team/user-java:latest
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: SQL_USER
              valueFrom:
                secretKeyRef:
                  name: mssqlconfig
                  key: username
            - name: SQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mssqlconfig 
                  key: password
            - name: SQL_SERVER
              valueFrom:
                secretKeyRef:
                  name: mssqlconfig
                  key: server
            - name: SQL_DBNAME
              valueFrom:
                secretKeyRef:
                  name: mssqlconfig
                  key: database
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: '500m'
              memory: 1G
            limits:
              cpu: '256'
              memory: 11400G
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer
  namespace: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: tripviewer
          image: registrybro8635.azurecr.io/bro_team/tripviewer:latest
          env:
            - name: TRIPS_API_ENDPOINT
              value: http://trips-service.api:80
            - name: USERPROFILE_API_ENDPOINT
              value: http://userprofile-service.api:80
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: '500m'
              memory: 1G
            limits:
              cpu: '256'
              memory: 11400G
---