apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: poi
          image: registrybro8635.azurecr.io/bro_team/poi:latest
          resources:
            requests:
              cpu: '200m'
              memory: 0.5G
            limits:
              cpu: '256'
              memory: 11400G
          ports:
            - containerPort: 80
          volumeMounts:
          - name: secrets-store01-inline
            mountPath: "/secrets"
            readOnly: true
      volumes:
        - name: secrets-store01-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-kvname-user-msi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trips
  template:
    metadata:
      labels:
        app: trips
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: trips
          image: registrybro8635.azurecr.io/bro_team/trips:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: '200m'
              memory: 0.5G
            limits:
              cpu: '256'
              memory: 11400G
          volumeMounts:
          - name: secrets-store01-inline
            mountPath: "/secrets"
            readOnly: true
      volumes:
        - name: secrets-store01-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-kvname-user-msi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: userprofile
          image: registrybro8635.azurecr.io/bro_team/userprofile:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: '200m'
              memory: 0.5G
            limits:
              cpu: '256'
              memory: 11400G
          volumeMounts:
          - name: secrets-store01-inline
            mountPath: "/secrets"
            readOnly: true
      volumes:
        - name: secrets-store01-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-kvname-user-msi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-java
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-java
  template:
    metadata:
      labels:
        app: user-java
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: user-java
          image: registrybro8635.azurecr.io/bro_team/user-java:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: '200m'
              memory: 0.5G
            limits:
              cpu: '256'
              memory: 11400G
          volumeMounts:
          - name: secrets-store01-inline
            mountPath: "/secrets"
            readOnly: true
      volumes:
        - name: secrets-store01-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-kvname-user-msi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer
  namespace: web
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: tripviewer
          image: registrybro8635.azurecr.io/bro_team/tripviewer:latest
          env:
            - name: TRIPS_API_ENDPOINT
              value: http://trips-service.api:80
            - name: USERPROFILE_API_ENDPOINT
              value: http://userprofile-service.api:80
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: '200m'
              memory: 0.5G
            limits:
              cpu: '256'
              memory: 11400G
